# -*- coding: utf-8 -*-
"""TavilyTest3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zPqmmW_lLoKyO8u934x37I-e7NrBEIdm
"""

import streamlit as st
import pandas as pd
from datetime import datetime
from transformers import pipeline

# Configure the page
st.set_page_config(
    page_title="Scholarship Finder",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Cache the scholarship data
@st.cache_resource
def load_scholarship_data():
    """Load and cache scholarship data."""
    data = {
        "Scholarship Name": [
            "Kuru Footsteps to Your Future Scholarship",
            "Alert1 Students for Seniors Scholarship",
            "Blankstyle Scholarship Opportunity",
            "Innovation in Education Scholarship",
            "The Bert & Phyllis Lamb Prize in Political Science",
            "New Beginnings Immigrant Scholarship",
        ],
        "Date Due": [
            "2024-12-20",
            "2025-01-10",
            "2024-12-31",
            "2024-10-15",
            "2025-02-14",
            "2024-10-18",
        ],
        "Summary": [
            "Awards $1,000 to high school seniors or college students pursuing academic goals.",
            "Provides $500 for students committed to improving senior care.",
            "A $1,000 bi-annual scholarship to support college expenses.",
            "Recognizes students with innovative projects that benefit their community.",
            "Honors excellence in Political Science with a prestigious award.",
            "Supports first-generation immigrant students pursuing higher education.",
        ],
    }
    df = pd.DataFrame(data)
    df["Date Due"] = pd.to_datetime(df["Date Due"])
    return df

# Cache the transformers pipelines
@st.cache_resource
def load_transformers():
    """Load and cache transformer models."""
    text_generator = pipeline("text-generation", model="EleutherAI/gpt-neo-1.3B")
    summarizer = pipeline("summarization", model="facebook/bart-large-cnn")
    return text_generator, summarizer

# Load cached resources
df = load_scholarship_data()
text_generator, summarizer = load_transformers()

# Sidebar Navigation
st.sidebar.title("📚 Navigation")
nav_option = st.sidebar.radio("Go to:", ["🏠 Home", "🎓 Find Scholarships", "📅 Calendar View", "ℹ️ About"])

# Home Page
if nav_option == "🏠 Home":
    st.title("🎓 Welcome to Scholarship Finder!")
    st.markdown("""
    Use this tool to explore scholarships tailored to your profile. Plan your applications effectively and make your academic dreams a reality.
    """)

# Scholarship Finder Page
elif nav_option == "🎓 Find Scholarships":
    st.header("🎓 Find Scholarships")
    name = st.text_input("Full Name")
    gpa = st.slider("GPA", 0.0, 4.0, 3.0, step=0.1)
    major = st.text_input("Major (e.g., Computer Science, Biology)")
    causes = st.multiselect("Causes or Interests", ["Community Service", "Diversity", "STEM", "Arts"])

    if st.button("Find Scholarships"):
        prompt = (
            f"Student Profile:\n"
            f"- Name: {name}\n"
            f"- GPA: {gpa}\n"
            f"- Major: {major}\n"
            f"- Causes: {', '.join(causes)}\n\n"
            f"Based on this profile, recommend scholarships and explain why they are a good fit. "
            f"Provide next steps for applying."
        )
        with st.spinner("Generating recommendations..."):
            response = text_generator(prompt, max_length=250, num_return_sequences=1)
        st.success("Here are your scholarship recommendations:")
        st.write(response[0]["generated_text"])

# Calendar View Page
elif nav_option == "📅 Calendar View":
    st.header("📅 Scholarship Calendar")
    col1, col2 = st.columns([2, 1])

    # Prepare events for the calendar
    events = {row["Date Due"].strftime("%Y-%m-%d"): row["Scholarship Name"] for _, row in df.iterrows()}

    # Display scholarships in two sections
    with col1:
        st.subheader("📋 Scholarships and Deadlines")
        for _, row in df.iterrows():
            st.markdown(
                f"**{row['Scholarship Name']}**  \n"
                f"🗓 **Due Date**: {row['Date Due'].strftime('%B %d, %Y')}\n"
                f"📖 **Summary**: {row['Summary']}\n"
            )

# About Page
elif nav_option == "ℹ️ About":
    st.header("ℹ️ About This App")
    st.markdown("""
    Scholarship Finder is designed to assist students in finding and applying for scholarships.
    Built with ❤️ to simplify your journey toward higher education.
    """)