# -*- coding: utf-8 -*-
"""TavilyTest2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zPqmmW_lLoKyO8u934x37I-e7NrBEIdm
"""

import streamlit as st
import pandas as pd
from datetime import datetime
from transformers import pipeline
from streamlit_calendar import calendar

# Configure the page
st.set_page_config(
    page_title="SCU Scholarship Finder",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Load Transformers Pipelines
@st.cache_resource
def load_transformers():
    text_generator = pipeline("text-generation", model="EleutherAI/gpt-neo-1.3B")
    return text_generator

text_generator = load_transformers()

# Scholarship Data
data = {
    "Scholarship Name": [
        "🎓 Kuru Footsteps to Your Future Scholarship",
        "💡 Alert1 Students for Seniors Scholarship",
        "⭐ Blankstyle Scholarship Opportunity #1",
        "🚀 Innovation In Education Scholarship",
        "📘 The Bert & Phyllis Lamb Prize in Political Science",
        "🌍 New Beginnings Immigrant Scholarship",
    ],
    "Date Due": [
        "2024-12-20",
        "2025-01-10",
        "2024-12-31",
        "2024-10-15",
        "2025-02-14",
        "2024-10-18",
    ],
    "Summary": [
        "This scholarship awards $1,000 to high school seniors or college students pursuing their academic goals. To apply: Prepare a personal statement highlighting your ambitions and submit your application by December 20, 2024.",
        "A $500 award for students committed to improving senior care. Action: Write a 300-word essay about your aspirations in this field. Submit your application by January 10, 2025.",
        "A $1,000 bi-annual scholarship to support college expenses. Actionable Steps: Share your accomplishments and explain how this scholarship will help you achieve your goals. Deadline: December 31, 2024.",
        "This $500 scholarship recognizes students with innovative projects that benefit their community. Action: Describe your project in detail and submit supporting documentation by October 15, 2024.",
        "The Bert & Phyllis Lamb Prize honors excellence in Political Science. Action: Submit a well-researched paper (up to 6,000 words) and an abstract by February 14, 2025.",
        "This scholarship supports first-generation immigrant students. Action: Write an essay about your immigrant experience and career aspirations. Deadline: October 18, 2024.",
    ],
}

# Convert data to a DataFrame
df = pd.DataFrame(data)
df["Date Due"] = pd.to_datetime(df["Date Due"])

# Sidebar Navigation
st.sidebar.title("📚 Navigation")
nav_option = st.sidebar.radio("Go to:", ["🏠 Home", "🎓 Find Scholarships", "📅 Calendar View", "ℹ️ About"])

# Home Page
if nav_option == "🏠 Home":
    st.title("🎓 Welcome to SCU Scholarship Finder!")
    st.subheader("Hello!👋")
    st.markdown("""
    **Discover scholarships tailored for Santa Clara University students.**
    Use this platform to explore funding opportunities, get personalized recommendations, and plan for upcoming deadlines.
    """)

# Scholarship Finder Page
elif nav_option == "🎓 Find Scholarships":
    st.header("🎓 Find Scholarships")
    st.subheader("📚 SCU Student Information")
    name = st.text_input("Full Name")
    gpa = st.slider("GPA", 0.0, 4.0, 3.0, step=0.1)
    major = st.selectbox("Select your academic major:", [
        "Computer Science", "Business Analytics", "Engineering", "Psychology", "Biology", "Undeclared", "Other"
    ])
    school_year = st.selectbox("Select your school year:", [
        "Freshman", "Sophomore", "Junior", "Senior", "Graduate Student", "Alumni"
    ])
    financial_need = st.selectbox("Financial Need?", ["Yes", "No"])
    ethnicity = st.text_input("Ethnicity (e.g., Hispanic, Asian)")
    residence_state = st.text_input("State of Residence (e.g., California)")
    causes = st.multiselect(
        "Causes or Interests:",
        ["Sustainability", "Community Service", "Diversity", "Social Justice", "STEM", "Arts"]
    )

    # Generate Recommendations
    if st.button("🔍 Find Scholarships"):
        student_profile = (
            f"Student Profile:\n"
            f"Name: {name}\n"
            f"GPA: {gpa}\n"
            f"Major: {major}\n"
            f"School Year: {school_year}\n"
            f"Financial Need: {financial_need}\n"
            f"Ethnicity: {ethnicity}\n"
            f"Residence State: {residence_state}\n"
            f"Causes: {', '.join(causes)}\n\n"
        )
        scholarship_context = "\n".join(
            f"Scholarship: {row['Scholarship Name']}\n"
            f"Summary: {row['Summary']}\n"
            f"Deadline: {row['Date Due'].strftime('%Y-%m-%d')}\n\n"
            for _, row in df.iterrows()
        )
        prompt = (
            f"Using the following student profile and available scholarships, "
            f"list scholarships that match the student. Include reasons why each scholarship is a good fit, "
            f"how the student should apply, and actionable next steps:\n\n"
            f"{student_profile}\n{scholarship_context}"
        )

        with st.spinner("Generating personalized recommendations..."):
            response = text_generator(prompt, max_length=300, num_return_sequences=1)
        st.success("Here are your scholarship recommendations:")
        st.write(response[0]["generated_text"])

# Calendar View Page
elif nav_option == "📅 Calendar View":
    st.title("📅 Scholarship Calendar")
    col1, col2 = st.columns([2, 1])

    # Events preparation
    events = {row["Date Due"].strftime("%Y-%m-%d"): row["Scholarship Name"] for _, row in df.iterrows()}

    with col1:
        st.subheader("📆 Calendar")
        selected_event = calendar(events)

    with col2:
        st.subheader("📋 All Scholarships")
        for _, row in df.iterrows():
            st.markdown(
                f"**{row['Scholarship Name']}**  \n"
                f"🗓 **Due Date**: {row['Date Due'].strftime('%B %d, %Y')}"
            )

# About Page
elif nav_option == "ℹ️ About":
    st.header("ℹ️ About This App")
    st.markdown("""
    **SCU Scholarship Finder** helps Santa Clara University students find and apply for scholarships.
    - Explore SCU-specific scholarships.
    - View a calendar of scholarship due dates.
    - Receive tailored recommendations based on your profile.

    Built with ❤️ for SCU students.
    """)