# -*- coding: utf-8 -*-
"""Tavily

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zPqmmW_lLoKyO8u934x37I-e7NrBEIdm
"""

import streamlit as st
from tavily import TavilyClient

# Setup Tavily API key
TAVILY_API_KEY = "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"  # Replace with your Tavily API key

# Initialize Tavily Client
tavily_client = TavilyClient(api_key=TAVILY_API_KEY)

# Function to query Tavily for scholarships
def fetch_scholarships_from_tavily(student_profile):
    try:
        query = (
            f"Find scholarships available for students attending Santa Clara University, "
            f"who are {student_profile['school_year']}s, studying {student_profile['major']} with a GPA of {student_profile['gpa']}. "
            f"Consider financial need: {student_profile['financial_need']} and interests in {', '.join(student_profile['causes'])}. "
            f"Focus on scholarships targeting {student_profile['ethnicity']} and residents of {student_profile['residence_state']}."
        )
        results = tavily_client.search(query=query, search_depth="advanced")["results"]
        return results
    except Exception as e:
        return f"Error fetching scholarships: {str(e)}"

# Streamlit App
def main():
    st.title("🎓 SCU Scholarship Finder")
    st.markdown("""
    Welcome to the SCU Scholarship Finder! This tool helps students attending Santa Clara University discover scholarships tailored to their profile and preferences.
    """)

    # Student Profile Input
    st.header("📝 Student Profile")
    name = st.text_input("Full Name")
    gpa = st.slider("GPA", 0.0, 4.0, 3.0, step=0.1)
    major = st.text_input("Major (e.g., Computer Science, Biology)")
    school_year = st.selectbox(
        "School Year",
        ["High School Senior", "College Freshman", "Sophomore", "Junior", "Senior", "Graduate Student"]
    )
    financial_need = st.selectbox("Financial Need?", ["Yes", "No"])
    ethnicity = st.text_input("Ethnicity (e.g., Hispanic, Asian)")
    residence_state = st.text_input("State of Residence (e.g., California)")
    causes = st.multiselect(
        "Causes or Interests",
        ["Community Service", "Sustainability", "Social Justice", "Diversity", "STEM", "Arts"]
    )

    # Fetch and Display Scholarships
    if st.button("Find Scholarships"):
        student_profile = {
            "name": name,
            "gpa": gpa,
            "major": major,
            "school_year": school_year,
            "financial_need": financial_need,
            "ethnicity": ethnicity,
            "residence_state": residence_state,
            "causes": causes
        }

        with st.spinner("Fetching scholarships from Tavily..."):
            scholarships = fetch_scholarships_from_tavily(student_profile)

        if isinstance(scholarships, str) and scholarships.startswith("Error"):
            st.error(scholarships)
        else:
            st.success("Here are the scholarships fetched from Tavily:")
            st.write(scholarships)

if __name__ == "__main__":
    main()